### ISSUE TITLE
关于 OSS 文件上传

### ISSUE THREAD

**Issue by Oscaner** [QNAV/RuoYi-X-Plus#52]
Hi QNAV,

我遇到一个问题 `文件存储服务类型无法找到!`
![image](https://github.com/QNAV/RuoYi-X-Plus/assets/26829325/3a9cb084-7244-46d1-801b-358838c28361)

经过调查发现在 `SysOssConfigServiceImpl` 的第 59 行，会判断 SysOssConfig 的 Status 是否为`0`，然后加入 Redis 缓存作为默认的 config。
<img width="772" alt="image" src="https://github.com/QNAV/RuoYi-X-Plus/assets/26829325/16c27bb2-d23f-48f8-bf47-76fe4517a136">

但是您的 SysOssConfig 的 status 是个 enum 类型，包含 `NORMAL` 和 `DISABLE`，并不包含 `0`。
<img width="772" alt="image" src="https://github.com/QNAV/RuoYi-X-Plus/assets/26829325/bb781fa4-fd5d-44f9-bd3f-ed7e62b4f372">

于是我去翻了一下 sync_plus.md 中的 RuoYi-Vue-Plus 仓库，发现 RuoYi-Vue-Plus 对于 status 的定义是 `是否为默认`，而您这边变成了 `是否启用`。
![image](https://github.com/QNAV/RuoYi-X-Plus/assets/26829325/9496390b-53fc-4b18-a9e5-83f29db4f2c7)

这也是导致文件上传不可用的原因，我不确定应该以哪种方式来修复该问题，所以只能提出来看看您有什么看法

**Comment by weibocy** [comment]
抱歉 很久没更新框架了，可以参考原作者框架或者直接使用原作者框架，我这个是改造来自用的
