### ISSUE TITLE
修改角色权限接口未报错，但查询不到修改后的角色权限

### ISSUE THREAD

**Issue by sushi-su** [QNAV/RuoYi-X-Plus#7]
修改的 cURL：
`curl 'https://test-ryx-admin-api.p.quicknav.cn/system/role/edit' \
  -H 'authority: test-ryx-admin-api.p.quicknav.cn' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: zh-CN,zh;q=0.9,en;q=0.8' \
  -H 'authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOiJzeXNfdXNlcjoxIiwicm5TdHIiOiJzd2xEeEdqdlg5VWV3ajN3T1ZkamJjbnVIeDR2Y3lyNiJ9.iSExbqJesLuymTJC30WunATM7CtRBzoAc2FSN-Zy84E' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'origin: http://localhost:8000' \
  -H 'pragma: no-cache' \
  -H 'referer: http://localhost:8000/' \
  -H 'sec-ch-ua: "Google Chrome";v="105", "Not)A;Brand";v="8", "Chromium";v="105"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36' \
  --data-raw '{"roleId":2,"menuIds":[1,100,1001,1002,1003,1004,1005,1006,1007,101,1008,1009,1010,1011,1012,102,1013,1014,1015,1016,103,1017,1018,1019,1020,104,1021,1022,1023,1024,1025,105,1026,1027,1028,1029,1030,106,1031,1032,1033,1034,1035,107,1036,1037,1038,1039,108,500,1040,1041,1042,501,1043,1044,1045,118,1600,1601,1602,1603,1604,1605,2,109,1046,1047,1048,111,113,117,120,3,114,115,1055,1056,1058,1057,1059,1060,116,4,5,1500,1501,1502,1503,1504,1505,1506,1507,1508,1509,1510,1511],"roleKey":"common","roleName":"普通角色","roleSort":2,"status":"0","menuCheckStrictly":false}' \
  --compressed`

查询的 cURL：
`curl 'https://test-ryx-admin-api.p.quicknav.cn/system/role/info?roleId=2' \
  -H 'authority: test-ryx-admin-api.p.quicknav.cn' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: zh-CN,zh;q=0.9,en;q=0.8' \
  -H 'authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOiJzeXNfdXNlcjoxIiwicm5TdHIiOiJzd2xEeEdqdlg5VWV3ajN3T1ZkamJjbnVIeDR2Y3lyNiJ9.iSExbqJesLuymTJC30WunATM7CtRBzoAc2FSN-Zy84E' \
  -H 'cache-control: no-cache' \
  -H 'origin: http://localhost:8000' \
  -H 'pragma: no-cache' \
  -H 'referer: http://localhost:8000/' \
  -H 'sec-ch-ua: "Google Chrome";v="105", "Not)A;Brand";v="8", "Chromium";v="105"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36' \
  --compressed`

**Comment by weibocy** [comment]
已解决
